# Generated by Django 5.0.1 on 2024-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240204_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choices',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'bronze'), ('S', 'silver'), ('G', 'gold')], default='B', max_length=1),
        ),
    ]
