# Generated by Django 5.0.3 on 2024-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
